name: Build and Push Docker image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Configura o Buildx (necessário para multi-arch)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Faz login no GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # Build e push multi-arch (AMD + ARM)
      - name: Build and push Docker image (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/csantos31/helm-demo-application:latest
          platforms: linux/amd64,linux/arm64
